---
name: "Deploy static content to Pages"

on: # yamllint disable-line
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "25 5 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      # Retrieve requests cache from artifacts
      - name: "Restore requests cache"
        id: "restore-cache"
        uses: "actions/cache/restore@v4"
        with:
          path: ".cache"
          key: "requests-cache"
      # Build HTML
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install Poetry"
        run: "pipx install poetry"
      - name: "Install Dependencies"
        run: "poetry install --no-root"
      - name: "Build static content"
        run: "poetry run python render.py"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Save requests cache to artifacts
      - name: "Store requests cache"
        uses: actions/cache/save@v4
        if: "steps.restore-cache.outputs.cache-hit != 'true'"
        with:
          path: ".cache"
          key: "requests-cache"
      # Deploy to Pages
      - name: "Setup Pages"
        uses: "actions/configure-pages@v5"
      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./output/"
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
